# Generated by Django 5.2.3 on 2025-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='name',
            field=models.CharField(default='admin', max_length=500),
            preserve_default=False,
        ),
    ]
