# Generated by Django 5.2.3 on 2025-09-13 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='recieve_by',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='text',
        ),
        migrations.AddField(
            model_name='chat',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recieve_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve_by', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chats',
            },
        ),
    ]
