# Generated by Django 5.2.3 on 2025-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userfriend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
