# Generated by Django 5.2.3 on 2025-09-27 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userchat_options_remove_userchat_recieve_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChat',
            new_name='UserFriend',
        ),
        migrations.AlterModelOptions(
            name='textchat',
            options={'verbose_name_plural': 'TextChats'},
        ),
    ]
