# Generated by Django 5.2.3 on 2025-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userfriend_is_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='is_request',
            field=models.BooleanField(default=True),
        ),
    ]
